Exec/DME_jet/PROB_2D.F
Exec/DME_jet/PROB_3D.F
Exec/DiffFlame/Prob_3d.F
Exec/DiffFlame/Prob_F.F
Exec/FlameInABox/Prob_2d.F90
Exec/FlameInABox/Prob_3d.F90
Exec/FlameInABox/Prob_F.F90
Exec/H_control/PROB_F.F
Exec/H_control/Prob_2d.F
Exec/H_control/Prob_3d.F
Source/ChemDriver/ChemDriver_2D.F90
Source/ChemDriver/ChemDriver_3D.F90
Source/ChemDriver/ChemDriver_F.F90
Source/PeleLM_2d.F90
Source/PeleLM_3d.F90

Should make everything compatible with new format of chemistry routines in PP dev. Tested on FlameInaBox example.

Dev compatible pp dev

---

Tools/Make/Make.PeleLM

[feature_FFCM1] Add the FFCM1 mechanism to the list of possible mech in

---

Exec/FlameInABox/Prob_2d.F90
Exec/FlameInABox/Prob_3d.F90
Exec/FlameInABox/Prob_F.F90
Exec/FlameInABox/probin.3d.test
Exec/H_control/Prob_2d.F90
Exec/H_control/Prob_3d.F90
Exec/H_control/Prob_F.F90
Source/PeleLM_2d.F90
Source/PeleLM_3d.F90
Source/PeleLM_F.F90
Tools/Make/Make.PeleLM

Comply with same branch in PelePhysics

Merge bigmech

---

Exec/RegTests/FlameSheet/GNUmakefile
Exec/RegTests/FlameSheet/inputs.3d-regt
Source/PeleLM.cpp
Source/PeleLM_F.H
Source/PeleLM_setup.cpp
Tools/Make/Make.PeleLM

TO go with same branch in PelePhysics. The following regTests are all green and happy:
COVO2_MU0
COVO2_MUEGLiB
FIAB2
FIAB2_restart
FIAB3
Do not merge yet, PLC should also be updated.

Feature clean cvode

---

Source/PeleLM.cpp
Source/PeleLM_F.H
Source/PeleLM_setup.cpp
Source/Prob_F.H
Source/Src_2d/Derive_PLM_2d.F90
Source/Src_2d/PeleLM_2d.F90
Source/Src_3d/Derive_PLM_3d.F90
Source/Src_3d/PeleLM_3d.F90

Added derive functions needed for our work.

Added derive functions needed for UNSW work

---

Source/PeleLM_setup.cpp
Source/Prob_F.H
Source/Src_nd/Make.package
Source/Src_nd/problem_derive_nd.F90
Tools/Make/Make.PeleLM

[feature_problem_derive] Add a problem derived function that can be used to build a UserDefined derived variable.

UserDefined derived variable.

---

Exec/RegTests/FlameSheet/Prob_nd.F90
Exec/RegTests/FlameSheet/inputs.2d-regt
Exec/RegTests/FlameSheet/probin.3d.test
Source/PeleLM_F.F90
Source/PeleLM_setup.cpp
Source/Prob_F.H
Source/Src_nd/Derive_PLM_nd.F90
Source/mod_Fvar_def.F90

Make a few modifications to the master branch in order to handle the triple flame tutorial.

Master triple flame

---

Source/PeleLM.cpp

1.0 for SDC. Restore some of the DBGSync showMF.

Fix deltaT sync setLevelBC and change forgotten 0.5 factor from CN into

---

Exec/RegTests/CoVo/inputs.2d-regt_amr

Reset COVO2D_1_AMR test to 3-level

---

Docs/source/ProblemSetup.rst
Docs/source/Tutorials_1.rst
Docs/source/Tutorials_3.rst

Update example code for init and bc to nd form.

Update doc a little

---

Exec/RegTests/FlameSheet/GNUmakefile
Source/PeleLM.cpp

otherwise, PeleLM will not compile !

update PeleLM to match the new IAMR

---

Exec/RegTests/EB_Convection_Wave_Species/GNUmakefile
Exec/RegTests/EB_Convection_Wave_Species/Prob_nd.F90
Exec/RegTests/EB_Convection_Wave_Species/inputs.2d-regt
Exec/RegTests/EB_Convection_Wave_Species/inputs.3d-regt
Exec/RegTests/EB_Convection_Wave_Species/probin.2d.regt
Exec/RegTests/EB_Convection_Wave_Temperature/GNUmakefile
Exec/RegTests/EB_Convection_Wave_Temperature/Prob_nd.F90
Exec/RegTests/EB_Convection_Wave_Temperature/inputs.2d-regt
Exec/RegTests/EB_Convection_Wave_Temperature/inputs.3d-regt
Exec/RegTests/EB_Convection_Wave_Temperature/probdata.F90
Exec/RegTests/EB_Convection_Wave_Temperature/probin.2d.regt
Exec/RegTests/EB_Convection_Wave_Temperature/user_defined_fcts_nd.F90
Source/PeleLM.cpp
Testing/Regression/PeleLM-tests.ini

As far as it has been tested, the version in this PR works with EB + AMR.
It has been tested up to 4 AMR lvls with DEBUG, OMP and fpe_trap, on non-reacting cases.

New way to advect Scalars + multiple bug fix

---

Source/PeleLM.cpp

- remove 0.5 coeffs on DT_pre/post, DH_pre/post for deltaT sync. Not
there in a SDC context.
- remove 0.5 coeff in differential_spec_diffuse_sync after the flux adjustment
for the same reasons as the first point.
- add missing setCoarseFineBC to the deltaTSyncOp for deltaT sync iter.
- add missing enthalpy flux increment of N/N+1 sync to FluxReg for N-1/N sync.

Fix further bugs on Ssync:

---

Source/PeleLM.cpp

This pull request makes the computation of S_tol_abs in the mac_sync deltaT iters EB aware. In certain cases, including covered cells can result in a very large S_tol_abs that tricks MLMG into thinking the system is sufficiently solved when it's not.

Cgilet fix sync

---

Docs/source/Model.rst

Update the model equation portion of the doc.

Update docu master based

---

Source/GPU_misc.H
Source/Make.package
Source/PeleLM.H
Source/PeleLM.cpp
Source/PeleLM_F.F90
Source/PeleLM_F.H
Source/PeleLM_K.H
Source/PeleLM_setup.cpp
Source/Src_nd/PeleLM_nd.F90

Note that the regression are likely to be broken because we don't get 0 diff

Merge last developments for gpu into development branch

---

Source/PeleLM_derive.cpp

Sorry, too many things at once. Use ASSERT before defining in_dat ...

Reorder ASSERT in PeleLM_derive.cpp

---

Source/PeleLM_derive.cpp

since you like em so much, I fixed em for you

Couple asserts were NUM_SPECIES + 1 when they shouldhave been NUM_SPECIES

---

Source/PeleLM_derive.cpp

Now that ncomp argument in derive functions has been properly sorted out.

Add/fix asserts (again) in derive functions

---

Source/PeleLM_K.H

Compatible with Anne's recent PR merge in PelePhysics

Adjust name of function to RTY2P

---

Source/PeleLM.cpp

I need those to track down some inactive GPU regions.

Add a couple of BL_PROFILE region to track down CPU/GPU comms.

---

Source/PeleLM.cpp
Source/PeleLM_setup.cpp

Goes with #93 of PelePhysics (although nothing is broken even if #93 is merged and not this one)

Add scaling on the GPU too

---

Source/PeleLM.H
Source/PeleLM.cpp

Remove calc_dsdt since PLM no longer uses it.

---

Source/PeleLM_bcfill.cpp
Source/PeleLM_setup.cpp

@emotheau Can you give this a try?

Fix press fill

---

Source/PeleLM.cpp

Tiny profiler in PeleLM::advance was messed up, with `diffusion` including `reaction`. A bit of a general clean up to highlight the various regions.

Clean up PeleLM::advance tiny profilers.

---

Docs/source/Tutorials_1.rst

- Update the description of the file in the Exec folder
- Update input keyword when necessary
TODO: AC picture need to be regenerated. Analysis section must be filled.

Update of the TripleFlame Tutorial
